/// Display names of the nutrients and vitamins tracked by the database.
const List<String> nutrientsAndVitamins = [
  'Protein',
  'Total lipid (fat)',
  'Energy',
  'Carbohydrate, by summation',
  'Sugars, Total NLEA',
  'Total fat (NLEA)',
  'Total sugar alcohols',
  'Folate, total',
  'Vitamin B-12',
  'Choline, total',
  'Fatty acids, total trans',
  'Fatty acids, total saturated',
  'Fatty acids, total monounsaturated',
  'Fatty acids, total polyunsaturated',
  'Sugars, total including NLEA',
  'Ash',
  'Nitrogen',
  'Alcohol, ethyl',
  'Water',
  'Sorbitol',
  'Caffeine',
  'Theobromine',
  'Carbohydrate, other',
  'Galactose',
  'Xylitol',
  'Ribose',
  'Calcium, Ca',
  'Chlorine, Cl',
  'Iron, Fe',
  'Magnesium, Mg',
  'Phosphorus, P',
  'Potassium, K',
  'Sodium, Na',
  'Sulfur, S',
  'Zinc, Zn',
  'Chromium, Cr',
  'Cobalt, Co',
  'Copper, Cu',
  'Fluoride, F',
  'Iodine, I',
  'Manganese, Mn',
  'Molybdenum, Mo',
  'Selenium, Se',
  'Boron, B',
  'Nickel, Ni',
  'Cholesterol',
  'Vitamin A, IU',
  'Retinol',
  'Vitamin A, RAE',
  'Vitamin E (alpha-tocopherol)',
  'Vitamin D (D2 + D3), International Units',
  'Vitamin D2 (ergocalciferol)',
  'Vitamin D3 (cholecalciferol)',
  'Vitamin D (D2 + D3)',
  'Vitamin E (label entry primarily)',
  'Vitamin E',
  'Vitamin C, total ascorbic acid',
  'Thiamin',
  'Riboflavin',
  'Niacin',
  'Pantothenic acid',
  'Vitamin B-6',
  'Biotin',
  'Folic acid',
  'Vitamin K (Menaquinone-4)',
  'Vitamin K (Dihydrophylloquinone)',
  'Vitamin K (phylloquinone)',
];
